version: '3.7'
services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: 'outsidedigital_db'
            POSTGRES_USER: 'outsidedigital_user'
            POSTGRES_PASSWORD: 'outsidedigital_password'
        ports:
            - '5438:5432'
        networks:
            - outsidedigitalnet
    api:
        build: ./api
        volumes:
            - ./api:/app
        working_dir: /app
        ports:
            - 127.0.0.1:3000:3000
        image: api-image
        container_name: api-container
        environment:
            PORT: 3000
            DATABASE_URL: postgres://outsidedigital_user:outsidedigital_password@db:5432/outsidedigital_db
            DB_USER: outsidedigital_user
            DB_HOST: db
            DB_NAME: outsidedigital_db
            DB_PASSWORD: outsidedigital_password
            DB_PORT: 5432
            SALT : 10
            JWT_SECRET_KEY: 21CCEF8EF77D51D568185B5DB59D5FD534A6944FE21B2ECB3B84CC01C4744479
        volumes:
            - ./api:/app
        depends_on:
            - 'db'
        command: bash -c "./wait-for-it.sh db:5432 && npm run migrate up && npm run start"
        networks:
            - outsidedigitalnet
    auth:
        build: ./auth
        volumes:
            - ./auth:/app
        working_dir: /app
        ports:
            - 127.0.0.1:3001:3001
        image: auth-image
        container_name: auth-container
        depends_on:
            - 'db'
        environment:
            PORT: 3001
            DB_USER: outsidedigital_user
            DB_HOST: db
            DB_NAME: outsidedigital_db
            DB_PASSWORD: outsidedigital_password
            DB_PORT: 5432
            SALT : 10
            JWT_EXPIRE_SESSION : 3600000
            JWT_EXPIRE_ACCESS_TOKEN : 1800000
            JWT_SECRET_KEY: 21CCEF8EF77D51D568185B5DB59D5FD534A6944FE21B2ECB3B84CC01C4744479
        volumes:
            - ./auth:/app
        command: bash -c "./wait-for-it.sh db:5432 && npm run start"
        networks:
            - outsidedigitalnet
networks:
    outsidedigitalnet:
        driver: bridge
